logging:
  level:
    com.avenga.steamclient: debug
steam-multi-client:
  log-on-details:
    -
      username: ${STEAM_USERNAME1}
      password: ${STEAM_PASSWORD1}
    -
      username: ${STEAM_USERNAME2}
      password: ${STEAM_PASSWORD2}
